# increase the memory available to gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric properties (see https://fabricmc.net/develop for the latest versions)
minecraft_version=1.21.8
yarn_mappings_version=1.21.8+build.1
fabric_loader_version=0.17.2
fabric_api_version=0.133.4+1.21.8
fabric_kotlin_version=1.13.6+kotlin.2.2.20

# mod properties
mod_id=mirage-minecraft-mod
mod_package=ai.decart.oasis
mod_version=1.1.6-android-fcl.1

# additional dependencies
webrtc_java_version=0.14.0
